#! /bin/sh

if [ $# -ne 1 ]; then
	>& 2 echo "usage: $(basename $0) pool-name"
	exit 1
fi

if [ -z "$SUDO_USER" ]; then
	echo "User unknown"
	exit 2
fi

base="$1"

set -x
truncate --size 2G "test-pool-$base.img"
zpool create "$base" "$PWD/test-pool-$base.img"
zfs allow -uld "$SUDO_USER" create "$base"
set +x

echo "export ZFS_TEST_BASE=$base"
