#!/usr/bin/env bash
set -euf -o pipefail
d=$(dirname $0)

# either use system definitions (found via pkg-config) or ones from the zfs source repo
ARGS=()
if [ "$#" -eq 1 ]; then
	ARGS+=(-I "$1/include" -I "$1/lib/libspl/include")
else
	ARGS+=($(pkg-config --cflags libzfs_core))
fi

set -x
bindgen "$d/wrapper.h" \
	-o "$d/src/bindings.rs" \
	--whitelist-function 'libzfs_core_.*' \
	--whitelist-function 'lzc_.*' \
	--whitelist-type 'dmu_replay_record' \
	--whitelist-type 'lzc_.*' \
	--whitelist-type 'pool_initialize_func.*' \
	--whitelist-type 'pool_trim_func.*' \
	--whitelist-type 'size_t' \
	--whitelist-type 'uchar_t' \
	--whitelist-type 'uint_t' \
	--whitelist-type 'vdev_.*' \
	--whitelist-type 'zfs_.*' \
	--whitelist-type 'zpool_.*' \
	--whitelist-var 'L2ARC_.*' \
	--whitelist-var 'SPA_.*' \
	--whitelist-var 'VDEV_.*' \
	--whitelist-var 'ZFS_.*' \
	--whitelist-var 'ZPL_.*' \
	--whitelist-var 'ZPOOL_.*' \
	--whitelist-var 'DEFAULT_PBKDF2_ITERATIONS' \
	--whitelist-var 'MIN_PBKDF2_ITERATIONS' \
	--default-enum-style moduleconsts \
	--rustified-enum 'zfs_errno_t' \
	--opaque-type dmu_replay_record \
	--blacklist-type 'va_list' \
	--blacklist-type '_IO_FILE' \
	--blacklist-type 'FILE' \
	--blacklist-type 'nvlist' \
	--blacklist-type '__uint[0-9]+_t' \
	--blacklist-type '__int[0-9]+_t' \
	--size_t-is-usize \
	-- \
	"${ARGS[@]}"
