#!/bin/sh
d=$(dirname $0)
bindgen "$d/wrapper.h" \
	-o "$d/src/bindings.rs" \
	--whitelist-function 'libzfs_.*' \
	--whitelist-function 'lzc_.*' \
	--whitelist-type 'lzc_.*' \
	--whitelist-type 'dmu_replay_record' \
	--whitelist-type 'uint_t' \
	--whitelist-type 'uchar_t' \
	--whitelist-type 'size_t' \
	--whitelist-type 'pool_trim_func.*' \
	--whitelist-type 'pool_initialize_func.*' \
	--constified-enum-module '.*' \
	--opaque-type dmu_replay_record \
	--blacklist-type 'va_list' \
	--blacklist-type '_IO_FILE' \
	--blacklist-type 'FILE' \
	--no-recursive-whitelist \
	--size_t-is-usize \
	-- \
	"$@"
