#!/usr/bin/env bash
set -euf -o pipefail
d=$(dirname $0)
e=false

ARGS=()
# either use system definitions (found via pkg-config) or ones from the zfs source repo
while getopts "hS:pR:" opt; do
	case "$opt" in
	S) # use the source code in location
		ARGS=(-I "$OPTARG/include" -I "$OPTARG/lib/libspl/include" -I "$OPTARG/lib/libspl/include/os/linux")
		;;
	p) # system pkg-config
		ARGS=($(pkg-config --cflags libzfs_core))
		;;
	R) # use this install location
		ARGS=(-I "$OPTARG/usr/include" -I "$OPTARG/usr/local/include" -I "$OPTARG/usr/local/include/libzfs" -I "$OPTARG/usr/local/include/libspl")
		;;
	\?) e=true ;;
	*) >&2 echo "programming bug: $opt unhandled"; exit 1;;
	esac
done

if $e; then
	>&2 echo "exiting due to previous errors"
	exit 1
fi

set -x
bindgen "$d/wrapper.h" \
	-o "$d/src/bindings.rs" \
	--whitelist-function 'libzfs_core_.*' \
	--whitelist-function 'lzc_.*' \
	--whitelist-type 'dmu_replay_record' \
	--whitelist-type 'lzc_.*' \
	--whitelist-type 'pool_initialize_func.*' \
	--whitelist-type 'pool_trim_func.*' \
	--whitelist-type 'size_t' \
	--whitelist-type 'uchar_t' \
	--whitelist-type 'uint_t' \
	--whitelist-type 'vdev_.*' \
	--whitelist-type 'zfs_.*' \
	--whitelist-type 'zpool_.*' \
	--whitelist-type 'drr_.*' \
	--whitelist-type 'dmu_.*' \
	--whitelist-type 'diff_type.*' \
	--whitelist-type 'zfs_.*' \
	--whitelist-type 'zinject.*' \
	--whitelist-type 'zio_.*' \
	--whitelist-type 'ddt_.*' \
	--whitelist-var 'L2ARC_.*' \
	--whitelist-var 'SPA_.*' \
	--whitelist-var 'VDEV_.*' \
	--whitelist-var 'ZFS_.*' \
	--whitelist-var 'ZPL_.*' \
	--whitelist-var 'ZPOOL_.*' \
	--whitelist-var 'DMU_.*' \
	--whitelist-var 'DRR_.*' \
	--whitelist-var 'DEFAULT_PBKDF2_ITERATIONS' \
	--whitelist-var 'MIN_PBKDF2_ITERATIONS' \
	--default-enum-style moduleconsts \
	--rustified-enum 'zfs_errno_t' \
	--opaque-type dmu_replay_record \
	--blacklist-type 'va_list' \
	--blacklist-type '_IO_FILE' \
	--blacklist-type 'FILE' \
	--blacklist-type 'nvlist' \
	--blacklist-type '__uint[0-9]+_t' \
	--blacklist-type '__int[0-9]+_t' \
	--size_t-is-usize \
	-- \
	"${ARGS[@]}"
