#!/bin/sh

os=$(uname -s)
case "$os" in
Darwin)
	export PKG_CONFIG_PATH=/usr/local/zfs/lib/pkgconfig
	sdkpath="$(xcrun --sdk macosx --show-sdk-path)"
	CFLAGS=(-I "$sdkpath/usr/include/")
	;;
*)
	CFLAGS=()
	;;
esac

d=$(dirname $0)
bindgen "$d/wrapper.h" \
	-o "$d/src/bindings.rs" \
	--whitelist-function 'nvlist_.*' \
	--whitelist-function 'nvpair_.*' \
	--whitelist-type 'nvlist_.*' \
	--whitelist-type 'uint_t' \
	--whitelist-type 'uchar_t' \
	--whitelist-type 'nv_alloc.*' \
	--whitelist-type 'boolean.*' \
	--whitelist-type 'nvpair.*' \
	--whitelist-type 'nvlist.*' \
	--whitelist-type 'hrtime.*' \
	--whitelist-type 'data_type_.*' \
	--constified-enum-module '.*' \
	--blacklist-type 'va_list' \
	--blacklist-type '_IO_FILE' \
	--blacklist-type 'FILE' \
	--no-recursive-whitelist \
	--raw-line \
'
// workaround for https://github.com/rust-lang/rust-bindgen/issues/1651
#[allow(unknown_lints)]
#[allow(deref_nullptr)]
pub type size_t = ::std::os::raw::c_ulong;' \
	-- `pkg-config libzfs_core --cflags` "${CFLAGS[@]}"
