#!/bin/sh
d=$(dirname $0)
bindgen "$d/wrapper.h" \
	-o "$d/src/bindings.rs" \
	--whitelist-function 'nvlist_.*' \
	--whitelist-function 'nvpair_.*' \
	--whitelist-type 'nvlist_.*' \
	--whitelist-type 'uint_t' \
	--whitelist-type 'uchar_t' \
	--whitelist-type 'nv_alloc.*' \
	--whitelist-type 'boolean.*' \
	--whitelist-type 'nvpair.*' \
	--whitelist-type 'nvlist.*' \
	--whitelist-type 'hrtime.*' \
	--whitelist-type 'data_type_.*' \
	--whitelist-type 'size_t' \
	--constified-enum-module '.*' \
	--blacklist-type 'va_list' \
	--blacklist-type '_IO_FILE' \
	--blacklist-type 'FILE' \
	--no-recursive-whitelist \
	-- `pkg-config libzfs_core --cflags`
