/* automatically generated by rust-bindgen 0.56.0 */

pub const ZFS_MAX_DATASET_NAME_LEN: u32 = 256;
pub mod boolean_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const B_FALSE: Type = 0;
    pub const B_TRUE: Type = 1;
}
pub type uchar_t = ::std::os::raw::c_uchar;
pub type uint_t = ::std::os::raw::c_uint;
pub type nvlist_t = nvlist;
pub mod pool_initialize_func {
    pub type Type = ::std::os::raw::c_uint;
    pub const POOL_INITIALIZE_START: Type = 0;
    pub const POOL_INITIALIZE_CANCEL: Type = 1;
    pub const POOL_INITIALIZE_SUSPEND: Type = 2;
    pub const POOL_INITIALIZE_FUNCS: Type = 3;
}
pub use self::pool_initialize_func::Type as pool_initialize_func_t;
pub mod pool_trim_func {
    pub type Type = ::std::os::raw::c_uint;
    pub const POOL_TRIM_START: Type = 0;
    pub const POOL_TRIM_CANCEL: Type = 1;
    pub const POOL_TRIM_SUSPEND: Type = 2;
    pub const POOL_TRIM_FUNCS: Type = 3;
}
pub use self::pool_trim_func::Type as pool_trim_func_t;
pub mod zpool_wait_activity_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const ZPOOL_WAIT_CKPT_DISCARD: Type = 0;
    pub const ZPOOL_WAIT_FREE: Type = 1;
    pub const ZPOOL_WAIT_INITIALIZE: Type = 2;
    pub const ZPOOL_WAIT_REPLACE: Type = 3;
    pub const ZPOOL_WAIT_REMOVE: Type = 4;
    pub const ZPOOL_WAIT_RESILVER: Type = 5;
    pub const ZPOOL_WAIT_SCRUB: Type = 6;
    pub const ZPOOL_WAIT_TRIM: Type = 7;
    pub const ZPOOL_WAIT_NUM_ACTIVITIES: Type = 8;
}
pub mod zfs_wait_activity_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const ZFS_WAIT_DELETEQ: Type = 0;
    pub const ZFS_WAIT_NUM_ACTIVITIES: Type = 1;
}
extern "C" {
    pub fn libzfs_core_init() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn libzfs_core_fini();
}
pub mod lzc_dataset_type {
    pub type Type = ::std::os::raw::c_uint;
    pub const LZC_DATSET_TYPE_ZFS: Type = 2;
    pub const LZC_DATSET_TYPE_ZVOL: Type = 3;
}
extern "C" {
    pub fn lzc_snapshot(
        arg1: *mut nvlist_t,
        arg2: *mut nvlist_t,
        arg3: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_create(
        arg1: *const ::std::os::raw::c_char,
        arg2: lzc_dataset_type::Type,
        arg3: *mut nvlist_t,
        arg4: *mut u8,
        arg5: uint_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_clone(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_promote(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_destroy_snaps(
        arg1: *mut nvlist_t,
        arg2: boolean_t::Type,
        arg3: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_bookmark(arg1: *mut nvlist_t, arg2: *mut *mut nvlist_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_get_bookmarks(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut nvlist_t,
        arg3: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_get_bookmark_props(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_destroy_bookmarks(
        arg1: *mut nvlist_t,
        arg2: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_load_key(
        arg1: *const ::std::os::raw::c_char,
        arg2: boolean_t::Type,
        arg3: *mut u8,
        arg4: uint_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_unload_key(arg1: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_change_key(
        arg1: *const ::std::os::raw::c_char,
        arg2: u64,
        arg3: *mut nvlist_t,
        arg4: *mut u8,
        arg5: uint_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_initialize(
        arg1: *const ::std::os::raw::c_char,
        arg2: pool_initialize_func_t,
        arg3: *mut nvlist_t,
        arg4: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_trim(
        arg1: *const ::std::os::raw::c_char,
        arg2: pool_trim_func_t,
        arg3: u64,
        arg4: boolean_t::Type,
        arg5: *mut nvlist_t,
        arg6: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_redact(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_snaprange_space(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut u64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_hold(
        arg1: *mut nvlist_t,
        arg2: ::std::os::raw::c_int,
        arg3: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_release(arg1: *mut nvlist_t, arg2: *mut *mut nvlist_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_get_holds(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
pub mod lzc_send_flags {
    pub type Type = ::std::os::raw::c_uint;
    pub const LZC_SEND_FLAG_EMBED_DATA: Type = 1;
    pub const LZC_SEND_FLAG_LARGE_BLOCK: Type = 2;
    pub const LZC_SEND_FLAG_COMPRESS: Type = 4;
    pub const LZC_SEND_FLAG_RAW: Type = 8;
    pub const LZC_SEND_FLAG_SAVED: Type = 16;
}
extern "C" {
    pub fn lzc_send(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
        arg4: lzc_send_flags::Type,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_send_resume(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
        arg4: lzc_send_flags::Type,
        arg5: u64,
        arg6: u64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_send_space(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: lzc_send_flags::Type,
        arg4: *mut u64,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dmu_replay_record {
    _unused: [u8; 0],
}
extern "C" {
    pub fn lzc_send_redacted(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
        arg4: lzc_send_flags::Type,
        arg5: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_send_resume_redacted(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
        arg4: lzc_send_flags::Type,
        arg5: u64,
        arg6: u64,
        arg7: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_receive(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut nvlist_t,
        arg3: *const ::std::os::raw::c_char,
        arg4: boolean_t::Type,
        arg5: boolean_t::Type,
        arg6: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_receive_resumable(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut nvlist_t,
        arg3: *const ::std::os::raw::c_char,
        arg4: boolean_t::Type,
        arg5: boolean_t::Type,
        arg6: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_receive_with_header(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut nvlist_t,
        arg3: *const ::std::os::raw::c_char,
        arg4: boolean_t::Type,
        arg5: boolean_t::Type,
        arg6: boolean_t::Type,
        arg7: ::std::os::raw::c_int,
        arg8: *const dmu_replay_record,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_receive_one(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut nvlist_t,
        arg3: *const ::std::os::raw::c_char,
        arg4: boolean_t::Type,
        arg5: boolean_t::Type,
        arg6: boolean_t::Type,
        arg7: ::std::os::raw::c_int,
        arg8: *const dmu_replay_record,
        arg9: ::std::os::raw::c_int,
        arg10: *mut u64,
        arg11: *mut u64,
        arg12: *mut u64,
        arg13: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_receive_with_cmdprops(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut nvlist_t,
        arg3: *mut nvlist_t,
        arg4: *mut u8,
        arg5: uint_t,
        arg6: *const ::std::os::raw::c_char,
        arg7: boolean_t::Type,
        arg8: boolean_t::Type,
        arg9: boolean_t::Type,
        arg10: ::std::os::raw::c_int,
        arg11: *const dmu_replay_record,
        arg12: ::std::os::raw::c_int,
        arg13: *mut u64,
        arg14: *mut u64,
        arg15: *mut u64,
        arg16: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_send_space_resume_redacted(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: lzc_send_flags::Type,
        arg4: u64,
        arg5: u64,
        arg6: u64,
        arg7: *const ::std::os::raw::c_char,
        arg8: ::std::os::raw::c_int,
        arg9: *mut u64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_send_progress(arg1: ::std::os::raw::c_int) -> u64;
}
extern "C" {
    pub fn lzc_exists(arg1: *const ::std::os::raw::c_char) -> boolean_t::Type;
}
extern "C" {
    pub fn lzc_rollback(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_rollback_to(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_rename(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_destroy(arg1: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_channel_program(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: u64,
        arg4: u64,
        arg5: *mut nvlist_t,
        arg6: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_channel_program_nosync(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: u64,
        arg4: u64,
        arg5: *mut nvlist_t,
        arg6: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_sync(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut nvlist_t,
        arg3: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_reopen(
        arg1: *const ::std::os::raw::c_char,
        arg2: boolean_t::Type,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_pool_checkpoint(arg1: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_pool_checkpoint_discard(
        arg1: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_wait(
        arg1: *const ::std::os::raw::c_char,
        arg2: zpool_wait_activity_t::Type,
        arg3: *mut boolean_t::Type,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_wait_tag(
        arg1: *const ::std::os::raw::c_char,
        arg2: zpool_wait_activity_t::Type,
        arg3: u64,
        arg4: *mut boolean_t::Type,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_wait_fs(
        arg1: *const ::std::os::raw::c_char,
        arg2: zfs_wait_activity_t::Type,
        arg3: *mut boolean_t::Type,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_set_bootenv(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const nvlist_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn lzc_get_bootenv(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
