on:
  push:
    branches-ignore:
      - '**.tmp'

name: codecov

jobs:
  codecov:
    runs-on: ubuntu-20.04
    env:
      ZFS_TEMPFS: tpool
    steps:
      - uses: actions/checkout@v1
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v1

      - name: Install cargo-binutils
        run: cargo install cargo-binutils

      # note: this works around the gha images sometimes not being up-to-date
      # with ubuntu mirrors, which can result in 404s when fetching packages
      - name: apt-get update
        run: sudo apt-get -o Acquire::Retries=3 update

      - name: Install dependencies
        run: sudo apt install libzfslinux-dev zfsutils-linux

      - name: Setup test pool
        run: sudo ./zfs-core/test-prepare "${ZFS_TEMPFS}"

      - name: Run tests & generate coverage info
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zinstrument-coverage'
          LLVM_PROFILE_FILE: 'rust-libzfs-%p-%m.profraw'

      - name: Merge coverage data
        run: cargo profdata -- merge -sparse -o rust-libzfs.profdata rust-libzfs-*.profraw
      - name: Generate coverage.txt
        run: llvm-cov show rust-libzffs.profmap -instr-profile "$1" "$dest" > coverage.txt
      - name: Fetch grcov
        run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      - name: Generate lcov.info
        run: ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
      - name: Archive lcov.info
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-lcov
          path: lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: true
      - name: Upload to codacy.com
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: lcov.info
      - name: Upload to coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
